### ISSUE TITLE
nodeBB 1.13.x compatible

### ISSUE THREAD

**Issue by NormandoHall** [boomzillawtf/nodebb-plugin-youtube-embed#14]
Two things.

1 - Fix regexp for P tags:

`YoutubeLite.youtubeUrl = /(<p.*>|^)((<a.*?href="((https?:\/\/(?:www\.)?)?youtube\.com\/\S*(?:(?:\/e(?:mbed))?\/|watch\?(?:\S*?&?v\=))|(https?:\/\/)?youtu\.be\/)(([a-zA-Z0-9_-]{6,11})(?:(?:[&\?#])([^"]+))?)"[^>]*?>)(\4\7)<\/a>)(<br\/?>|<\/p>)/m;`

2 - There is no button parse because the new html sanitizacion:

https://github.com/NodeBB/NodeBB/issues/7872

Thank you

**Comment by NormandoHall** [comment]
About html sanitization, I fixed adding the function to the plugin:

In plugin.json adding this hook at top:

`{ "hook": "filter:sanitize.config", "method": "filterSanitizeConfig", "priority": 10 },`

and this function in library.js

```
YoutubeLite.filterSanitizeConfig  = function (sanitizeConfig, callback) {
    sanitizeConfig.allowedTags.push('svg', 'path');
    sanitizeConfig.allowedAttributes.svg = sanitizeConfig.allowedAttributes.svg || [];
    sanitizeConfig.allowedAttributes.svg.push('viewbox', 'height', 'version', 'width' );
    sanitizeConfig.allowedAttributes.path = sanitizeConfig.allowedAttributes.path || [];
    sanitizeConfig.allowedAttributes.path.push('class', 'd', 'fill', 'fill-opacity' );
	sanitizeConfig.allowedAttributes.button.push('onclick', 'aria-*');
	callback(null, sanitizeConfig);
};
```

Also change the attribute `viewBox` to `viewbox` then render as `viewBox`

**Comment by bulunluo** [comment]
> Two things.
> 
> 1 - Fix regexp for P tags:
> 
> `YoutubeLite.youtubeUrl = /(<p.*>|^)((<a.*?href="((https?:\/\/(?:www\.)?)?youtube\.com\/\S*(?:(?:\/e(?:mbed))?\/|watch\?(?:\S*?&?v\=))|(https?:\/\/)?youtu\.be\/)(([a-zA-Z0-9_-]{6,11})(?:(?:[&\?#])([^"]+))?)"[^>]*?>)(\4\7)<\/a>)(<br\/?>|<\/p>)/m;`
> 
> 2 - There is no button parse because the new html sanitizacion:
> 
> [NodeBB/NodeBB#7872](https://github.com/NodeBB/NodeBB/issues/7872)
> 
> Thank you

hello, could you tell me where should I add this command
`YoutubeLite.youtubeUrl = /(<p.*>|^)((<a.*?href="((https?:\/\/(?:www\.)?)?youtube\.com\/\S*(?:(?:\/e(?:mbed))?\/|watch\?(?:\S*?&?v\=))|(https?:\/\/)?youtu\.be\/)(([a-zA-Z0-9_-]{6,11})(?:(?:[&\?#])([^"]+))?)"[^>]*?>)(\4\7)<\/a>)(<br\/?>|<\/p>)/m;`

**Comment by bulunluo** [comment]
> About html sanitization, I fixed adding the function to the plugin:
> 
> In plugin.json adding this hook at top:
> 
> `{ "hook": "filter:sanitize.config", "method": "filterSanitizeConfig", "priority": 10 },`
> 
> and this function in library.js
> 
> ```
> YoutubeLite.filterSanitizeConfig  = function (sanitizeConfig, callback) {
>     sanitizeConfig.allowedTags.push('svg', 'path');
>     sanitizeConfig.allowedAttributes.svg = sanitizeConfig.allowedAttributes.svg || [];
>     sanitizeConfig.allowedAttributes.svg.push('viewbox', 'height', 'version', 'width' );
>     sanitizeConfig.allowedAttributes.path = sanitizeConfig.allowedAttributes.path || [];
>     sanitizeConfig.allowedAttributes.path.push('class', 'd', 'fill', 'fill-opacity' );
> 	sanitizeConfig.allowedAttributes.button.push('onclick', 'aria-*');
> 	callback(null, sanitizeConfig);
> };
> ```
> 
> Also change the attribute `viewBox` to `viewbox` then render as `viewBox`

hello, i followed all modifications, but it doesn't show button on post, please

**Comment by NormandoHall** [comment]
> hello, i followed all modifications, but it doesn't show button on post, please

Hello. You only see the play button if you have set the youtube api key

**Comment by bulunluo** [comment]
> > hello, i followed all modifications, but it doesn't show button on post, please
> 
> Hello. You only see the play button if you have set the youtube api key

i resolved with another plugin, anywhere, thank so much.
