### ISSUE TITLE
Bug with Material Design Theme.

### ISSUE THREAD

**Issue by Master-Antonio** [boomzillawtf/nodebb-plugin-youtube-embed#2]
Plugin : nodebb-plugin-youtube-embed
There is a little bug of graphic in the groups with the theme  : Material Design Theme.
Theme Link : https://github.com/pichalite/nodebb-theme-material#readme
![image](https://cloud.githubusercontent.com/assets/9674957/17950914/a34a5c50-6a5e-11e6-8e25-c1813696ceb9.png)
![image](https://cloud.githubusercontent.com/assets/9674957/17950924/b10ea5c6-6a5e-11e6-930a-1990958a7b08.png)

**Comment by Master-Antonio** [comment]
I think that the sizes good are this.
    width: 550px;
    padding-bottom: 310px;
![image](https://cloud.githubusercontent.com/assets/9674957/17951189/85916fa8-6a60-11e6-817b-4c8c5f95b032.png)

**Comment by Master-Antonio** [comment]
Can you apply these changes?

**Comment by boomzillawtf** [comment]
The size is based on the youtube thumbnails. I've added a change that we've also applied locally, which is `max-size: 100%` to prevent it from running off the screen. We originally applied that for mobile users, but I think it will work for this, too.
